name: docfx-action
author: David Hernando (forked from Niklas Mollenhauer)
description: Runs docfx as a GitHub Action and publish the result in GitHub Pages.

runs:
  using: docker
  image: 'Dockerfile'

branding:
  icon: book
  color: green
